#theme: jekyll-theme-minimal

#logo: /assets/img/RS.PNG

# Site settings
title: Dr. Reema Singh
#email: res498@usask.ca
#description: Bioinformatician and Data Manager/Staff Scientist at VIDO
theme: minima

include:
 - _pages
 
