#theme: jekyll-theme-minimal
theme: jekyll-theme-dinky
logo: /assets/img/RS.PNG

# Site settings
title: Dr. Reema Singh
twitter:
  username: reemasingh28

#email: res498@usask.ca
#description: Bioinformatician and Data Manager/Staff Scientist at VIDO
#theme: minima

include:
 - _pages
 
